### ISSUE TITLE
Time to attach some CI to it so that we can get in the early habit of the niceties of Go :)

### ISSUE THREAD

**Issue by edwarnicke** [godirect/hoststack#4]
## yamllint
I'd recommend adding a [yamllint](https://github.com/adrienverge/yamllint) job to keep yaml files (like your Github Actions) clean.  An example of doing this can be found:

https://github.com/edwarnicke/govpp/blob/acad58175c1ac6bdf936b83e3e0345537ecbcc9d/.github/workflows/ci.yaml#L15-L25

And you will want to grab the [yamllint.conf](https://github.com/edwarnicke/govpp/blob/acad58175c1ac6bdf936b83e3e0345537ecbcc9d/.ci/yamllint.yml)

## golanglint-ci
I'd recommend adding [golanglint-ci](https://github.com/golangci/golangci-lint) to lint you code.  An example can be found here:

https://github.com/edwarnicke/vpphelper/blob/f914b171f679c081a095df9711e20c967881c736/.github/workflows/ci.yaml#L35-L44

and you will need a [.golangci.yml](https://github.com/edwarnicke/vpphelper/blob/main/.golangci.yml) file

## Keeping go.mod and go.sum tidy

https://github.com/edwarnicke/vpphelper/blob/f914b171f679c081a095df9711e20c967881c736/.github/workflows/ci.yaml#L46-L69

## Checking that your code builds:

https://github.com/edwarnicke/vpphelper/blob/f914b171f679c081a095df9711e20c967881c736/.github/workflows/ci.yaml#L20-L34

Note: You will have to adapt this one, because the `./...` recursive decent won't traverse down directories that start with `_`

## Look at Docker build and push for your containers

https://github.com/networkservicemesh/cmd-forwarder-vpp/blob/1c8b7e90aebb18ad1a3c991663dea646bc93b1be/.github/workflows/ci.yaml#L124-L151

(this may require a lot of adaptation).

**Comment by harshgondaliya** [comment]
@edwarnicke I am stuck at the following two parts:

1. I am unable to find a command that will recursively traverse all the sub-directories and files (including hidden ones)
2. From my understanding of what I am supposed to do for "docker" job, I have written the following code.
```yaml
docker:
    name: Docker Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v1
        with:
          go-version: 1.15.3
      - name: Build container
        run: docker build ./_examples/app-attach
      - name: Run tests
        run: docker run --privileged $(docker build -q ./_examples/app-attach --target runtime)
      - name: Find merged PR
        if: github.event_name == 'push' && github.ref == 'refs/heads/exercies'
        uses: jwalton/gh-find-current-pr@v1
        id: findPr
        with:
          github-token: ${{ github.token }}
      - name: Publish Image
        if: github.event_name == 'push' && github.ref == 'refs/heads/exercies' && success() && steps.findPr.outputs.number
        uses: matootie/github-docker@v3.0.0
        with:
          accessToken: ${{ github.token }}
          tag: |
            pr-${{ steps.findPr.outputs.pr }}
            commit-${{ github.sha }}
            latest

```
I just assumed that we want to publish app-attach application image. Is the above code one that you needed?
